dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings
  corpus:
    root: ..      # CHANGE THIS: path to the folder with ptb3-wsj-*.conllx files
    train_path: ptb3-wsj-train.conllx
    dev_path: ptb3-wsj-dev.conllx
    test_path: ptb3-wsj-test.conllx
  embeddings:
    type: token 
    root: ..      # CHANGE THIS: path to the folder with raw*..elmo-layers.hdf5 files
    train_path: raw.train.elmo-layers.hdf5
    dev_path: raw.dev.elmo-layers.hdf5
    test_path: raw.test.elmo-layers.hdf5
  batch_size: 20
  dataset_size: 40000
model:
  hidden_dim: 1024 # ELMo hidden dim
  model_type: identity 
  use_disk: True
  model_layer: 0 # ELMo: {0, 1, 2}  # CHANGE THIS: insert your layer
regimen:
  type: online_coding #zznone, bayes, online_coding
  inds: 0.001,0.002,0.004,0.008,0.016,0.032,0.0625,0.125,0.25,0.5,1
probe:
  task_signature: word_label 
  type: none # none
  task_name: corrupted-part-of-speech
  maximum_rank: 1000                # CHANGE THIS (IF YOU REALLY WANT)
  psd_parameters: True
  diagonal: False
  hidden_layers: 0
  dropout: 0
  params_path: predictor.params
  misc:
    rand_label_condition_length: 1
    corrupted_token_percent: 1.0
  probe_spec:
    probe_hidden_layers: 2          # CHANGE THIS (IF YOU REALLY WANT)
probe_training:
  epochs: 40
  loss: cross-entropy
  weight_decay: 0.0
  learning_rate: 0.001
reporting:
  fixed_directory: online_l0_control   # CHANGE THIS: output dir with ckpts and logs
  root: .
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictionsl
  reporting_methods:
    - label_accuracy





