confounder_lang: fr
source_lang: es
target_lang: en
direction_causal: False
batch_size: 10
dummy: False
trim_length: 400
probe:
  task_name: translation
  params_path: predictor.params
regimen:
  type: online_coding
  inds: 0.001,0.002,0.004,0.008,0.016,0.032,0.0625,0.125,0.25,0.5,1
probe_training:
  epochs: 5
  loss: cross-entropy
  weight_decay: 0.0
  learning_rate: 0.00003
gpus: 0,1



